# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: Stamp mode
        options:
        - none
        - patch
        - minor
        - major
      prerelease_name:
        description: Prerelease name
      release_candidate:
        description: Is it Release Candidate
        type: boolean
      release:
        description: Do you want to Release
        type: boolean
      app_name:
        description: App name
        required: true

jobs:
  build_pkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0

    - id: foo
      uses: progovoy/vmn-action@vmna_0.1.29
      with:
        release-candidate: ${{inputs.release_candidate}}
        release: ${{inputs.release}}
        prerelease-name: ${{inputs.prerelease_name}}
        stamp-mode: ${{inputs.version_type}}
        app-name: ${{inputs.app_name}}

     
    - name: Use the output from vmn action
      run: |
        echo "${{steps.foo.outputs.verstr}}"
