name: Run Stamp Without Release Candidate

on:
  workflow_dispatch:
    inputs:
      app_name:
        type: string
        description: App name
        required: true
      stamp_mode:
        type: choice
        description: Release mode
        options:
        - patch
        - minor
        - major
        required: true
      show_log_on_error: 
        type: boolean
        description: Do you want to see the VMN log on error?
        default: false
      debug_mode: 
        type: boolean
        description: Show extra logs?
        default: false
      install_nonstable_vmn_version: 
        type: boolean
        description: Install latest RC version of VMN
        default: false    


jobs:
  build_pkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0

    - id: foo
      uses: progovoy/vmn-action@vmna_0.1.73
      with:
        app-name: ${{ inputs.app_name }}
        do-stamp: true
        stamp-mode: ${{ inputs.stamp_mode }}
        show-log-on-error: ${{ inputs.show_log_on_error }}
        debug-mode: ${{ inputs.debug_mode }}
        install-nonstable-vmn-version: ${{ inputs.install_nonstable_vmn_version }}
      env:
        GITHUB_TOKEN: ${{ github.token }} 
      
    - name: Use the output from vmn action
      run: |
        echo "The Version is: ${{ steps.foo.outputs.verstr }}"
        echo "Is the code dirty?: ${{ steps.foo.outputs.dirty }}"
        echo "Is the app in Release Candidate Mode: ${{ steps.foo.outputs.is_in_rc_mode }}"
        echo "The whole vmn show for you to parser is: ${{ steps.foo.outputs.verbose_yaml }}"