name: Run Stamp Non-First Release Candidate

on:
  workflow_dispatch:
    inputs:
      app_name:
        type: string
        description: App name
        required: true
      gen_template_path: 
        type: string
        description: Path for Jinja2 Template file
      gen_output_path: 
        type: string
        description: Path for output file
      gen_custom_yaml_path: 
        type: string
        description: Path for custom YAML file
      show_log_on_error: 
        type: boolean
        description: Do you want to see the VMN log on error?
        default: false
      debug_mode: 
        type: boolean
        description: Show extra logs?
        default: false
      install_nonstable_vmn_version: 
        type: boolean
        description: Install latest RC version of VMN
        default: false    


jobs:
  build_pkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0

    - id: foo
      uses: progovoy/vmn-action@vmna_0.1.70
      with:
        app-name: ${{inputs.app_name}}
        do-gen: true
        gen-template-path: ${{ inputs.gen_template_path }}
        gen-output-path: ${{ inputs.gen_output_path }}
        gen-custom-yaml-path: ${{ inputs.gen_custom_yaml_path }}
        show-log-on-error: ${{ inputs.show_log_on_error }}
        debug-mode: ${{ inputs.debug_mode }}
        install-nonstable-vmn-version: ${{ inputs.install_nonstable_vmn_version }}
      env:
        GITHUB_TOKEN: ${{ github.token }} 
      
    - name: Use the output from vmn action
      run: |
        cat ${{ inputs.gen_output_path }}