# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: Version type
        options:
        - patch
        - minor
        - major
        required: true

jobs:
  build_pkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - id: foo
      uses: progovoy/vmn-stamp-action@vmn_stamp_action_0.6.14
      with:
        release-mode: ${{inputs.version_type}}
        app-name: 'bla1'
     
    - name: Publish a Python distribution to PyPI
      run: |
        echo "${{steps.foo.outputs.verstr}}"
